pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                bat "mvn -f Project clean"
            }
        }
        stage('Build') {
            steps {
                bat "mvn -f Project compile"
            }
        }
        stage('Test') {
            steps {
                bat "mvn -f Project test"
            }
        }
    }
}
