pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                sh "mvn -f Project clean"
            }
        }
        stage('Build') {
            steps {
                sh "mvn -f Project compile"
            }
        }
        stage('Test') {
            steps {
                sh "mvn -f Project test"
            }
        }
        stage('shutdown current app') {
            steps{
                script{
                    try{
                        sh "curl -X POST http://localhost:8080/"
                    }catch(Exception e){
                    }
                }
            }
        }
        stage('test ls'){
                    steps{
                        sh "ls -R"
                    }
                }
        stage('copy app'){
            steps{
                sh "cp Project/target/Project-0.0.1-SNAPSHOT.jar ./"
            }
        }
    }
}
